### ISSUE TITLE
Author parsing

### ISSUE THREAD

**Issue by Cj-Malone** [feedbin/refresher#8]
When parsing Atom files if the `entry` doesn't have an `author` tag then it should check for a `source` element and use its `author`, if that's not there then it should use the `feed` `author`. [Spec](https://tools.ietf.org/html/rfc4287#section-4.2.1)

Currently the parser just attempts to use `entry` `author`, and the itunes author if that's available.

**Comment by benubois** [comment]
Hi,

Feedbin uses [Feedjira](https://github.com/feedjira/feedjira) for parsing. This would be more appropriately opened there. 

Thanks!
